### ISSUE TITLE
Stable Release + Official Repositories

### ISSUE THREAD

**Issue by dev-rke** [Borim7/radio-tray#3]
Happy new Year @Borim7,

i will test the application in the next days.
Until now i was a huge fan of the old radiotray based on Python 2.7, so i am interested if you are planning to provide a prebuild debian package, e.g. via github actions or e.g. a ppa.
Furthermore i'd like to know if you plan to publish your current version to e.g. to the Ubuntu Universe Repository or as a snap package.

Do you plan to maintain this application in future?

I'd like to see radiotray or something similar back in the official repositories, as it is a very easy to use and super lightweight application.

Thank you and all the best for 2021! :-)

**Comment by Borim7** [comment]
Hey,

a good question... to be honest I have stumbled into the position to be a developer of radiotray. I am using radiotray since years and I was sad, when I heard, that it will removed from the official package repositories. So I have started porting it to python3 without any motivation to be an "offical developer".

In the end I was surprised that the old devs removed the radiotray code repository. As I had the code repository locally, I put it with my changes online here.

Still I like radiotray and will continue using it. So I probably will stick to radiotray and will keep it going.

Providing debian packages should be no problem. The build process is already reworked and it is the install method I use. The current master state is quite stable and master should always represent a stable state. 

It would be cool if radiotray will be again in the official package repository, but at least for now I do not know what is necessary to achieve this. If someone know how this can be done, any help is appreciated ;)

I wont create a snap, the overhead is in my eyes in no relation to the lightweight radiotray.

I want to test my latest changes for some time and than I will create a release including debian package. For now radiotray will only be availble here on github.

Cheers and let us hope 2021 will be better ^^

**Comment by dev-rke** [comment]
Hey,

thanks for your reply. I don't want you to be an "official" maintainer. ;-)
I just would like to see the application back in the repos - even when it is not maintained on a regular basis.
The old application stayed there for more than five years without any updates, so i think this is already a pretty stable implementation. In the meantime i looked at radiotray-ng, but it misses some nice features like autoplay on startup.

I agree to keep radiotray small and lightweight, but unfortunately the new standard on Ubuntu is to provide snaps, even software packages are only provided via snapstore. So to get it back running on Ubuntu the easiest solution is via snap.

The quick alternative would be to publish the debian package in an launchpad ppa:
https://help.launchpad.net/Packaging/PPA
So anybody can install the package from the repository.

In my opinion a ppa or a snap will be the simplest solution to keep users updated, e.g. if you want to integrate a patch in future.

My point is: i usually use several machines, so it is easier to install software and get updates via standard package managers than from github.

**Comment by Borim7** [comment]
Providing a ppa should possible. I currently testing how ppa uploads are done.

**Comment by dev-rke** [comment]
Cool, i am glad to hear that. :-)
In the meantime i found out the right docs how to publish a new software package for Ubuntu, seems to be a bit more complicated:
https://packaging.ubuntu.com/html/packaging-new-software.html

But I think the first step should be the ppa until stability, performance etc. is perfect.

**Comment by Borim7** [comment]
If you want you can test the ppa: https://launchpad.net/~borim/+archive/ubuntu/radiotray
or `sudo add-apt-repository ppa:borim/radiotray`

It is the current master with some changes needed by the ppa process. After some cleanup I will update the repo here, but not now ;)

**Comment by dev-rke** [comment]
Wohoooo! Thanks!
Unfortunately i am not able to use it as it is not signed, i get an error when running `apt update`.
I have to find out how to install packages from an unsigned repo...

Ah update:
> After you've activated your PPA, uploading its first package causes Launchpad to start generating your key, which can take up to a couple of hours to complete. 
https://help.launchpad.net/Packaging/PPA#Your_PPA.27s_key

Seems i have to wait...i will give you later or tomorrow feedback.
Thank you very much, 2021 seems to start great! ;-)

**Comment by dev-rke** [comment]
Whoop Whoop!
Installation works! :-)
Thank you very much.
My recommendation would be to mention the new PPA within the README and propably within the repository description.

**Comment by Borim7** [comment]
Good to hear, I think the readme is the right place for this information
